In [2]:
import tensorflow as tf
import pandas as pd
import numpy as np
import os
import models
import importlib
os.environ['KMP_DUPLICATE_LIB_OK']='True'
from matplotlib import pyplot as plt

In [23]:
importlib.reload(models)

<module 'models' from '/Users/varun/School/CS182/finalproj/CS182-Spring2020-NLP-Project/models.py'>

In [4]:
df = pd.read_csv("dataset-binary.csv")
df = df.dropna()

In [5]:
train_df = df.iloc[int(len(df) * .8):]
test_df = df.iloc[:int(len(df) * .8)]

In [6]:
training_reviews, training_stars, test_reviews, test_stars = models.get_fit_samples(train_df, test_df, 10000)

In [13]:
l1, l21, l22, l31, tokenizer = models.tree_model(5, training_reviews, test_reviews, training_stars, test_stars)

Train on 8000 samples, validate on 2000 samples
Epoch 1/5
8000/8000 - 131s - loss: 0.5106 - accuracy: 0.7520 - val_loss: 0.3361 - val_accuracy: 0.8700
Epoch 2/5
8000/8000 - 117s - loss: 0.3246 - accuracy: 0.8677 - val_loss: 0.2613 - val_accuracy: 0.8990
Epoch 3/5
8000/8000 - 117s - loss: 0.2657 - accuracy: 0.8928 - val_loss: 0.2387 - val_accuracy: 0.9085
Epoch 4/5
8000/8000 - 118s - loss: 0.2259 - accuracy: 0.9103 - val_loss: 0.2375 - val_accuracy: 0.9120
Epoch 5/5
8000/8000 - 118s - loss: 0.2010 - accuracy: 0.9218 - val_loss: 0.2225 - val_accuracy: 0.9140
Train on 8000 samples, validate on 2000 samples
Epoch 1/5
8000/8000 - 129s - loss: 0.4761 - accuracy: 0.7753 - val_loss: 0.2734 - val_accuracy: 0.8780
Epoch 2/5
8000/8000 - 119s - loss: 0.2933 - accuracy: 0.8752 - val_loss: 0.2497 - val_accuracy: 0.9050
Epoch 3/5
8000/8000 - 119s - loss: 0.3077 - accuracy: 0.8739 - val_loss: 0.2141 - val_accuracy: 0.9170
Epoch 4/5
8000/8000 - 119s - loss: 0.2228 - accuracy: 0.9111 - val_loss: 0.1865 

In [14]:
tree_model = models.construct_tree_model(l1, l21, l22, l31)

In [29]:
padded = models.create_padded_from_tokenizer(tokenizer, training_reviews[0:200])

In [17]:
tree_model(padded[2])

1

In [20]:
corr = 0
comp = train_df[10000:11000][["stars_1.0", "stars_2.0", "stars_3.0", "stars_4.0", "stars_5.0"]].values
for i in range(1000):
    guess = tree_model(padded[i])
    if comp[i][guess - 1] == 1:
        corr += 1
corr / 1000

0.704

In [45]:
m1, m2, m3, m4, m5 = models.flat_model(5, training_reviews, test_reviews, training_stars, test_stars)

Train on 8000 samples, validate on 2000 samples
Epoch 1/5
8000/8000 - 134s - loss: 0.5093 - accuracy: 0.7731 - val_loss: 0.3206 - val_accuracy: 0.8545
Epoch 2/5
8000/8000 - 118s - loss: 0.5271 - accuracy: 0.8114 - val_loss: 0.3018 - val_accuracy: 0.8635
Epoch 3/5
8000/8000 - 119s - loss: 0.3530 - accuracy: 0.8497 - val_loss: 0.3228 - val_accuracy: 0.8930
Epoch 4/5
8000/8000 - 118s - loss: 0.3353 - accuracy: 0.8814 - val_loss: 0.3227 - val_accuracy: 0.9075
Epoch 5/5
8000/8000 - 118s - loss: 0.3855 - accuracy: 0.8876 - val_loss: 0.3370 - val_accuracy: 0.9115
Train on 8000 samples, validate on 2000 samples
Epoch 1/5
8000/8000 - 127s - loss: 0.9903 - accuracy: 0.9345 - val_loss: 1.1342 - val_accuracy: 0.9265
Epoch 2/5
8000/8000 - 119s - loss: 1.0033 - accuracy: 0.9346 - val_loss: 1.1337 - val_accuracy: 0.9265
Epoch 3/5
8000/8000 - 120s - loss: 1.0027 - accuracy: 0.9350 - val_loss: 1.1337 - val_accuracy: 0.9265
Epoch 4/5
8000/8000 - 118s - loss: 1.0026 - accuracy: 0.9350 - val_loss: 1.1337 

In [46]:
m1.predict(padded[0])

array([[1.2706668]], dtype=float32)

In [19]:
l1.save("l1.h5")
l21.save("l21.h5")
l22.save("l22.h5")
l31.save("l31.h5")

In [24]:
model, history = models.kaggle_model(5, training_reviews, test_reviews, training_stars, test_stars)

Train on 8000 samples, validate on 2000 samples
Epoch 1/5
8000/8000 - 147s - loss: 0.3726 - accuracy: 0.8438 - val_loss: 0.2896 - val_accuracy: 0.8824
Epoch 2/5
8000/8000 - 133s - loss: 0.2800 - accuracy: 0.8888 - val_loss: 0.2387 - val_accuracy: 0.9042
Epoch 3/5
8000/8000 - 132s - loss: 0.2506 - accuracy: 0.8996 - val_loss: 0.2261 - val_accuracy: 0.9111
Epoch 4/5
8000/8000 - 131s - loss: 0.2308 - accuracy: 0.9066 - val_loss: 0.2242 - val_accuracy: 0.9085
Epoch 5/5
8000/8000 - 140s - loss: 0.2188 - accuracy: 0.9101 - val_loss: 0.2259 - val_accuracy: 0.9081


In [33]:
temp = model.predict(padded.squeeze())

In [32]:
training_stars[0]

array([1, 0, 0, 0, 0])

In [34]:
temp = np.array([np.argmax(i) for i in temp])

In [36]:
out = []
for i in temp:
    x = [0, 0, 0, 0, 0]
    x[i] = 1
    out.append(np.array(x))
np.array(out)

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0,

In [45]:
corr = 0
for i in range(200):
    if list(training_stars[i]) == list(out[i]):
        corr += 1
corr / 200

0.775

array([1, 0, 0, 0, 0])